export default [
  {
    id: 'mamas_virtual_concert',
    title: 'Mama Saturn\'s Virtual Concert',
    subtitle: {
      chanel: 'Tanerélle',
      views: '3,401,111 views',
      date: 'Apr 27, 2020',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=i2XUrySbdUE',
    img: 'https://i.ytimg.com/vi_webp/i2XUrySbdUE/mqdefault.webp',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwngMxnxLcEzoXddMzRSviXgiL2BpqW_lHoktrNJQWA=s176-c-k-c0xffffffff-no-rj-mo',
    length: '30:16',
  },
  {
    id: 'toronto_shche',
    title: 'Вибори треба скасувати! Хай все вирішить алгоритм. ЩЕ з Максом Щербиною',
    subtitle: {
      chanel: 'Телебачення Торонто',
      views: '104K views',
      date: '2 days ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=xqg7Jixeqv8',
    img: 'https://i.ytimg.com/vi/xqg7Jixeqv8/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAzbPMi5ak0B6OhA350EXApoYjKCw',
    logo: 'https://yt3.ggpht.com/a-/AOh14GiLKAe7pKwVUoX8KILgPRx_NJWucafcjt7ZDg=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '20:14',
  },
  {
    id: 'the_interviewer_kalush',
    title: 'KALUSH про наркотики, alyona alyona та TikTok Поплавського. Зе Інтерв\'юер',
    subtitle: {
      chanel: 'Зе Интервьюер',
      views: '42K views',
      date: '1 week ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=ID6rN7mOyrc',
    img: 'https://i.ytimg.com/vi/ID6rN7mOyrc/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAfsdUjnJlWvfK2WdcHU55jGMElJg',
    logo: 'https://yt3.ggpht.com/a-/AOh14Gj-mF_pgKZIcpFnMJvyyir6DVkvzFjuFsdo5Q=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '1:05:56',
  },
  {
    id: 'the_weeknd',
    title: 'Save Your Tears / In Your Eyes (Live on The 2020 American Music Awards)',
    subtitle: {
      chanel: 'The Weeknd',
      views: '3.9M views',
      date: '4 days ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=ID6rN7mOyrc',
    img: 'https://i.ytimg.com/vi/f-g_SHNv5NI/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBFa1GHOaqpgOAVYn87Dff-tWVNgg',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnjZKsNOcODaa15Dy0LSVqPHw8AMhat0BHXa5c9d=s88-c-k-c0x00ffffff-no-rj',
    length: '3:53',
  },
  {
    id: 'vdud_markov',
    title: 'Марков – как живет русская провинция / вДудь',
    subtitle: {
      chanel: 'вДудь',
      views: '9.6M views',
      date: '1 week ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=QDHYQ9Nd-GU',
    img: 'https://i.ytimg.com/vi/QDHYQ9Nd-GU/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAyIlo1o4bM9apqZVCo7KqZTgVu1w',
    logo: 'https://yt3.ggpht.com/a-/AOh14Gh0IehoxL212Fnto8IyCYp8fA44DLKCOh5C=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '2:09:03',
  },
  {
    id: 'beyonce_reedom',
    title: 'Beyoncé - Freedom (Acapella Lemonade)',
    subtitle: {
      chanel: 'Beyoncé Barcelona',
      views: '156K views',
      date: '5 months ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=Wx5vlcXRCro',
    img: 'https://i.ytimg.com/vi/Wx5vlcXRCro/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAdjl97eW11ZlgmRSMlH7XXdMzBqA',
    logo: 'https://yt3.ggpht.com/a-/AOh14GgSlggYMwf0sW9LeMzK7bOVlSyj_knK18AWkg=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '0:56',
  },
  {
    id: 'hitchcock',
    title: '96-Minute \'Masterclass\' Interview with Alfred Hitchcock on Filmmaking (1976)',
    subtitle: {
      chanel: 'Eyes On Cinema',
      views: '432K views',
      date: '5 years ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=DDvC6tzrJro',
    img: 'https://i.ytimg.com/vi/DDvC6tzrJro/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCUMpFUVcAxnBaONbSGcv-JiIIWEQ',
    logo: 'https://yt3.ggpht.com/a-/AOh14GjeWGmEG2-xSB6KTj8WUL-5Q4Izd5RRSz3ViA=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '1:35:52',
  },
  {
    id: 'kinopoisk',
    title: 'Как снимает Франсуа Озон',
    subtitle: {
      chanel: 'КиноПоиск',
      views: '80K views',
      date: '1 week ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=LFH4IsqJhu0',
    img: 'https://i.ytimg.com/vi/LFH4IsqJhu0/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAp7G6t5DIxLptolP0NUuE1uBLdOA',
    logo: 'https://yt3.ggpht.com/a-/AOh14GhXSBs0KmmkJdme4dZiA8cGEepkRiUAO7StDw=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '10:20',
  },
  {
    id: 'pumas',
    title: 'Black Pumas - Colors (Official Live Session)',
    subtitle: {
      chanel: 'Black Pumas',
      views: '48K views',
      date: 'Jul 22, 2019',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=0G383538qzQ&list=PLEyJvb9d3wUaz20eZAA-dnzlc5Qf-RCpY&index=5',
    img: 'https://i.ytimg.com/vi/0G383538qzQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKCjKEY2uHMDxVI-K1WirV8bdnZQ',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwniMnAkO72ITEy_2yFBKUEJEUPh8zJrdRluhOAaT=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '6:47',
  },
  {
    id: 'kiwanuka',
    title: 'Michael Kiwanuka - Hero (Official Video)',
    subtitle: {
      chanel: 'Black Pumas',
      views: '480K views',
      date: 'Oct 15, 2019',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=fb_S4aWI6Og&list=PLEyJvb9d3wUaz20eZAA-dnzlc5Qf-RCpY&index=4',
    img: 'https://i.ytimg.com/vi/fb_S4aWI6Og/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDHywCou1txAtnMsAFTP34Pwxjgfw',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnipjuwzzL4iMbmCrBfz2UBi0XxpVe2dooyw_BKN=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '4:50',
  },
  {
    id: 'kwaye',
    title: 'KWAYE - RUN (Official Music Video)',
    subtitle: {
      chanel: 'KWAYE',
      views: '130K views',
      date: 'Nov 17, 2020',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=J3r_PGArsRE',
    img: 'https://i.ytimg.com/vi/J3r_PGArsRE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC7RkpBwjpoTBY-fzR6k3F5Vm5zQg',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnhkQ8obI97qK4bYxhqZLwlWY0CIRbEw6lXbMZQFmA=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '4:50',
  },
  {
    id: 'mamas_virtual_concert',
    title: 'Mama Saturn\'s Virtual Concert',
    subtitle: {
      chanel: 'Tanerélle',
      views: '3,401,111 views',
      date: 'Apr 27, 2020',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=i2XUrySbdUE',
    img: 'https://i.ytimg.com/vi_webp/i2XUrySbdUE/mqdefault.webp',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwngMxnxLcEzoXddMzRSviXgiL2BpqW_lHoktrNJQWA=s176-c-k-c0xffffffff-no-rj-mo',
    length: '30:16',
  },
  {
    id: 'toronto_shche',
    title: 'Вибори треба скасувати! Хай все вирішить алгоритм. ЩЕ з Максом Щербиною',
    subtitle: {
      chanel: 'Телебачення Торонто',
      views: '104K views',
      date: '2 days ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=xqg7Jixeqv8',
    img: 'https://i.ytimg.com/vi/xqg7Jixeqv8/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAzbPMi5ak0B6OhA350EXApoYjKCw',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwngMxnxLcEzoXddMzRSviXgiL2BpqW_lHoktrNJQWA=s176-c-k-c0xffffffff-no-rj-mo',
    length: '20:14',
  },
  {
    id: 'the_interviewer_kalush',
    title: 'KALUSH про наркотики, alyona alyona та TikTok Поплавського. Зе Інтерв\'юер',
    subtitle: {
      chanel: 'Зе Интервьюер',
      views: '42K views',
      date: '1 week ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=ID6rN7mOyrc',
    img: 'https://i.ytimg.com/vi/ID6rN7mOyrc/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAfsdUjnJlWvfK2WdcHU55jGMElJg',
    logo: 'https://yt3.ggpht.com/a-/AOh14Gj-mF_pgKZIcpFnMJvyyir6DVkvzFjuFsdo5Q=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '1:05:56',
  },
  {
    id: 'the_weeknd',
    title: 'Save Your Tears / In Your Eyes (Live on The 2020 American Music Awards)',
    subtitle: {
      chanel: 'The Weeknd',
      views: '3.9M views',
      date: '4 days ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=ID6rN7mOyrc',
    img: 'https://i.ytimg.com/vi/f-g_SHNv5NI/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBFa1GHOaqpgOAVYn87Dff-tWVNgg',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnjZKsNOcODaa15Dy0LSVqPHw8AMhat0BHXa5c9d=s88-c-k-c0x00ffffff-no-rj',
    length: '3:53',
  },
  {
    id: 'vdud_markov',
    title: 'Марков – как живет русская провинция / вДудь',
    subtitle: {
      chanel: 'вДудь',
      views: '9.6M views',
      date: '1 week ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=QDHYQ9Nd-GU',
    img: 'https://i.ytimg.com/vi/QDHYQ9Nd-GU/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAyIlo1o4bM9apqZVCo7KqZTgVu1w',
    logo: 'https://yt3.ggpht.com/a-/AOh14Gh0IehoxL212Fnto8IyCYp8fA44DLKCOh5C=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '2:09:03',
  },
  {
    id: 'beyonce_reedom',
    title: 'Beyoncé - Freedom (Acapella Lemonade)',
    subtitle: {
      chanel: 'Beyoncé Barcelona',
      views: '156K views',
      date: '5 months ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=Wx5vlcXRCro',
    img: 'https://i.ytimg.com/vi/Wx5vlcXRCro/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAdjl97eW11ZlgmRSMlH7XXdMzBqA',
    logo: 'https://yt3.ggpht.com/a-/AOh14GgSlggYMwf0sW9LeMzK7bOVlSyj_knK18AWkg=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '0:56',
  },
  {
    id: 'hitchcock',
    title: '96-Minute \'Masterclass\' Interview with Alfred Hitchcock on Filmmaking (1976)',
    subtitle: {
      chanel: 'Eyes On Cinema',
      views: '432K views',
      date: '5 years ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=DDvC6tzrJro',
    img: 'https://i.ytimg.com/vi/DDvC6tzrJro/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCUMpFUVcAxnBaONbSGcv-JiIIWEQ',
    logo: 'https://yt3.ggpht.com/a-/AOh14GjeWGmEG2-xSB6KTj8WUL-5Q4Izd5RRSz3ViA=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '1:35:52',
  },
  {
    id: 'kinopoisk',
    title: 'Как снимает Франсуа Озон',
    subtitle: {
      chanel: 'КиноПоиск',
      views: '80K views',
      date: '1 week ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=LFH4IsqJhu0',
    img: 'https://i.ytimg.com/vi/LFH4IsqJhu0/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAp7G6t5DIxLptolP0NUuE1uBLdOA',
    logo: 'https://yt3.ggpht.com/a-/AOh14GhXSBs0KmmkJdme4dZiA8cGEepkRiUAO7StDw=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '10:20',
  },
  {
    id: 'pumas',
    title: 'Black Pumas - Colors (Official Live Session)',
    subtitle: {
      chanel: 'Black Pumas',
      views: '48K views',
      date: 'Jul 22, 2019',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=0G383538qzQ&list=PLEyJvb9d3wUaz20eZAA-dnzlc5Qf-RCpY&index=5',
    img: 'https://i.ytimg.com/vi/0G383538qzQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKCjKEY2uHMDxVI-K1WirV8bdnZQ',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwniMnAkO72ITEy_2yFBKUEJEUPh8zJrdRluhOAaT=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '6:47',
  },
  {
    id: 'kiwanuka',
    title: 'Michael Kiwanuka - Hero (Official Video)',
    subtitle: {
      chanel: 'Black Pumas',
      views: '480K views',
      date: 'Oct 15, 2019',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=fb_S4aWI6Og&list=PLEyJvb9d3wUaz20eZAA-dnzlc5Qf-RCpY&index=4',
    img: 'https://i.ytimg.com/vi/fb_S4aWI6Og/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDHywCou1txAtnMsAFTP34Pwxjgfw',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnipjuwzzL4iMbmCrBfz2UBi0XxpVe2dooyw_BKN=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '4:50',
  },
  {
    id: 'kwaye',
    title: 'KWAYE - RUN (Official Music Video)',
    subtitle: {
      chanel: 'KWAYE',
      views: '130K views',
      date: 'Nov 17, 2020',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=J3r_PGArsRE',
    img: 'https://i.ytimg.com/vi/J3r_PGArsRE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC7RkpBwjpoTBY-fzR6k3F5Vm5zQg',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnhkQ8obI97qK4bYxhqZLwlWY0CIRbEw6lXbMZQFmA=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '4:50',
  },
  {
    id: 'mamas_virtual_concert',
    title: 'Mama Saturn\'s Virtual Concert',
    subtitle: {
      chanel: 'Tanerélle',
      views: '3,401,111 views',
      date: 'Apr 27, 2020',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=i2XUrySbdUE',
    img: 'https://i.ytimg.com/vi_webp/i2XUrySbdUE/mqdefault.webp',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwngMxnxLcEzoXddMzRSviXgiL2BpqW_lHoktrNJQWA=s176-c-k-c0xffffffff-no-rj-mo',
    length: '30:16',
  },
  {
    id: 'toronto_shche',
    title: 'Вибори треба скасувати! Хай все вирішить алгоритм. ЩЕ з Максом Щербиною',
    subtitle: {
      chanel: 'Телебачення Торонто',
      views: '104K views',
      date: '2 days ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=xqg7Jixeqv8',
    img: 'https://i.ytimg.com/vi/xqg7Jixeqv8/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAzbPMi5ak0B6OhA350EXApoYjKCw',
    logo: 'https://yt3.ggpht.com/a-/AOh14GiLKAe7pKwVUoX8KILgPRx_NJWucafcjt7ZDg=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '20:14',
  },
  {
    id: 'the_interviewer_kalush',
    title: 'KALUSH про наркотики, alyona alyona та TikTok Поплавського. Зе Інтерв\'юер',
    subtitle: {
      chanel: 'Зе Интервьюер',
      views: '42K views',
      date: '1 week ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=ID6rN7mOyrc',
    img: 'https://i.ytimg.com/vi/ID6rN7mOyrc/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAfsdUjnJlWvfK2WdcHU55jGMElJg',
    logo: 'https://yt3.ggpht.com/a-/AOh14Gj-mF_pgKZIcpFnMJvyyir6DVkvzFjuFsdo5Q=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '1:05:56',
  },
  {
    id: 'the_weeknd',
    title: 'Save Your Tears / In Your Eyes (Live on The 2020 American Music Awards)',
    subtitle: {
      chanel: 'The Weeknd',
      views: '3.9M views',
      date: '4 days ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=ID6rN7mOyrc',
    img: 'https://i.ytimg.com/vi/f-g_SHNv5NI/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBFa1GHOaqpgOAVYn87Dff-tWVNgg',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnjZKsNOcODaa15Dy0LSVqPHw8AMhat0BHXa5c9d=s88-c-k-c0x00ffffff-no-rj',
    length: '3:53',
  },
  {
    id: 'vdud_markov',
    title: 'Марков – как живет русская провинция / вДудь',
    subtitle: {
      chanel: 'вДудь',
      views: '9.6M views',
      date: '1 week ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=QDHYQ9Nd-GU',
    img: 'https://i.ytimg.com/vi/QDHYQ9Nd-GU/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAyIlo1o4bM9apqZVCo7KqZTgVu1w',
    logo: 'https://yt3.ggpht.com/a-/AOh14Gh0IehoxL212Fnto8IyCYp8fA44DLKCOh5C=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '2:09:03',
  },
  {
    id: 'beyonce_reedom',
    title: 'Beyoncé - Freedom (Acapella Lemonade)',
    subtitle: {
      chanel: 'Beyoncé Barcelona',
      views: '156K views',
      date: '5 months ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=Wx5vlcXRCro',
    img: 'https://i.ytimg.com/vi/Wx5vlcXRCro/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAdjl97eW11ZlgmRSMlH7XXdMzBqA',
    logo: 'https://yt3.ggpht.com/a-/AOh14GgSlggYMwf0sW9LeMzK7bOVlSyj_knK18AWkg=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '0:56',
  },
  {
    id: 'hitchcock',
    title: '96-Minute \'Masterclass\' Interview with Alfred Hitchcock on Filmmaking (1976)',
    subtitle: {
      chanel: 'Eyes On Cinema',
      views: '432K views',
      date: '5 years ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=DDvC6tzrJro',
    img: 'https://i.ytimg.com/vi/DDvC6tzrJro/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCUMpFUVcAxnBaONbSGcv-JiIIWEQ',
    logo: 'https://yt3.ggpht.com/a-/AOh14GjeWGmEG2-xSB6KTj8WUL-5Q4Izd5RRSz3ViA=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '1:35:52',
  },
  {
    id: 'kinopoisk',
    title: 'Как снимает Франсуа Озон',
    subtitle: {
      chanel: 'КиноПоиск',
      views: '80K views',
      date: '1 week ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=LFH4IsqJhu0',
    img: 'https://i.ytimg.com/vi/LFH4IsqJhu0/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAp7G6t5DIxLptolP0NUuE1uBLdOA',
    logo: 'https://yt3.ggpht.com/a-/AOh14GhXSBs0KmmkJdme4dZiA8cGEepkRiUAO7StDw=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '10:20',
  },
  {
    id: 'pumas',
    title: 'Black Pumas - Colors (Official Live Session)',
    subtitle: {
      chanel: 'Black Pumas',
      views: '48K views',
      date: 'Jul 22, 2019',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=0G383538qzQ&list=PLEyJvb9d3wUaz20eZAA-dnzlc5Qf-RCpY&index=5',
    img: 'https://i.ytimg.com/vi/0G383538qzQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAKCjKEY2uHMDxVI-K1WirV8bdnZQ',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwniMnAkO72ITEy_2yFBKUEJEUPh8zJrdRluhOAaT=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '6:47',
  },
  {
    id: 'kiwanuka',
    title: 'Michael Kiwanuka - Hero (Official Video)',
    subtitle: {
      chanel: 'Black Pumas',
      views: '480K views',
      date: 'Oct 15, 2019',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=fb_S4aWI6Og&list=PLEyJvb9d3wUaz20eZAA-dnzlc5Qf-RCpY&index=4',
    img: 'https://i.ytimg.com/vi/fb_S4aWI6Og/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDHywCou1txAtnMsAFTP34Pwxjgfw',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnipjuwzzL4iMbmCrBfz2UBi0XxpVe2dooyw_BKN=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '4:50',
  },
  {
    id: 'kwaye',
    title: 'KWAYE - RUN (Official Music Video)',
    subtitle: {
      chanel: 'KWAYE',
      views: '130K views',
      date: 'Nov 17, 2020',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=J3r_PGArsRE',
    img: 'https://i.ytimg.com/vi/J3r_PGArsRE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC7RkpBwjpoTBY-fzR6k3F5Vm5zQg',
    logo: 'https://yt3.ggpht.com/ytc/AAUvwnhkQ8obI97qK4bYxhqZLwlWY0CIRbEw6lXbMZQFmA=s176-c-k-c0xffffffff-no-nd-rj-mo',
    length: '4:50',
  },
  {
    id: 'vdud_markov',
    title: 'Марков – как живет русская провинция / вДудь',
    subtitle: {
      chanel: 'вДудь',
      views: '9.6M views',
      date: '1 week ago',
      isOfficial: true,
    },
    url: 'https://www.youtube.com/watch?v=QDHYQ9Nd-GU',
    img: 'https://i.ytimg.com/vi/QDHYQ9Nd-GU/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAyIlo1o4bM9apqZVCo7KqZTgVu1w',
    logo: 'https://yt3.ggpht.com/a-/AOh14Gh0IehoxL212Fnto8IyCYp8fA44DLKCOh5C=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '2:09:03',
  },
  {
    id: 'beyonce_reedom',
    title: 'Beyoncé - Freedom (Acapella Lemonade)',
    subtitle: {
      chanel: 'Beyoncé Barcelona',
      views: '156K views',
      date: '5 months ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=Wx5vlcXRCro',
    img: 'https://i.ytimg.com/vi/Wx5vlcXRCro/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAdjl97eW11ZlgmRSMlH7XXdMzBqA',
    logo: 'https://yt3.ggpht.com/a-/AOh14GgSlggYMwf0sW9LeMzK7bOVlSyj_knK18AWkg=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '0:56',
  },
  {
    id: 'hitchcock',
    title: '96-Minute \'Masterclass\' Interview with Alfred Hitchcock on Filmmaking (1976)',
    subtitle: {
      chanel: 'Eyes On Cinema',
      views: '432K views',
      date: '5 years ago',
      isOfficial: false,
    },
    url: 'https://www.youtube.com/watch?v=DDvC6tzrJro',
    img: 'https://i.ytimg.com/vi/DDvC6tzrJro/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCUMpFUVcAxnBaONbSGcv-JiIIWEQ',
    logo: 'https://yt3.ggpht.com/a-/AOh14GjeWGmEG2-xSB6KTj8WUL-5Q4Izd5RRSz3ViA=s68-c-k-c0x00ffffff-no-rj-mo',
    length: '1:35:52',
  },
]